package project;
// TokenType.java
public enum TokenType {
    START, END, IF, OTHERWISE, FOR, REPEAT, UNTIL, CONTINUE, STOP, METHOD, OUTPUT, GET, SHOW,CHOOSE_WHAT,CONVERT_TO,
    NUMBER_TYPE, DECIMAL_TYPE, TEXT_TYPE, BINARY_TYPE, LIST_TYPE, PAIR_MAP_TYPE,PICK,
    TRUE, FALSE, NONE,
    LEN, SORT, KEY, VALUE,TO_TEXT,
    IDENTIFIER, NUMBER, DECIMAL, TEXT,
    ASSIGN, PLUS, MINUS, MULT, DIV, EXPONENT, MOD, FLOOR_DIV,PLUS_ASSIGN, MINUS_ASSIGN,MULT_ASSIGN,
    AND, OR, NOT, EQ, NEQ, LT, GT, LEQ, GEQ,
    BITWISE_AND, BITWISE_OR, BITWISE_XOR, BITWISE_NOT, LSHIFT, RSHIFT, S_NOT,QUOTE,
    LPAREN, RPAREN, LCURLY, RCURLY, LBRACKET, RBRACKET, COMMA, SEMI, COLON, DOT,
    MCOMMENT,SCOMMENT, EOF, ERROR, REMOVE,ADD,CONTAINS,CLEAR,KEYS,VALUES,
}