package project;
// TokenType.java
enum TokenType {
    START, END, IF, OTHERWISE, FOR, REPEAT, REPEAT_UNTIL, CONTINUE, STOP, METHOD, OUTPUT, GET, SHOW,
    NUMBER_TYPE, DECIMAL_TYPE, TEXT_TYPE, BINARY_TYPE, LIST_TYPE, PAIR_MAP_TYPE,
    TRUE, FALSE, NONE,
    IDENTIFIER, NUMBER, DECIMAL, STRING,
    ASSIGN, PLUS, MINUS, MULT, DIV, EXPONENT, MOD, FLOOR_DIV,
    AND, OR, NOT, EQ, NEQ, LT, GT, LEQ, GEQ,
    BITWISE_AND, BITWISE_OR, BITWISE_XOR, BITWISE_NOT, LSHIFT, RSHIFT,
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET, COMMA, SEMI, COLON, DOT,
    COMMENT, EOF, ERROR
}